### ISSUE TITLE
能否缩放图片？

### ISSUE THREAD

**Issue by yang-ling** [Kenshin/simptab#10]
我上传了一些图片，但是有些图片过大，显示不全，能否自动缩放以适应窗口呢？

类似桌面背景提供缩放，剪切，平铺功能。

**Comment by Kenshin** [comment]
会考虑加入这个功能，只是没有想好如何设计，当然，这个功能肯定是放到侧栏里面。因为要保持SimpTab的简洁，最好不要过多干预图片，这样看起来比较"重"。

我需要在简洁（拿来就用）、干净和功能之间把握平衡。如果你有更好的想法，可以一起讨论。 :)

**Comment by yang-ling** [comment]
我的意思是自动使图片适应浏览器窗口，不需要设定。因为图片过大显示不全的话，看起来怪怪的。

我想，缩放，剪切，平铺这三个功能，只要缩放就好，就是说，展示图片时，如果图片过大或者过小，就缩放图片，同时保持图片比例，当然这样可能不会完全占满窗口，不过我觉得还好。

**Comment by Kenshin** [comment]
嗯，已经放到`Feature`里面了，会考虑优化方式。 :)

**Comment by Kenshin** [comment]
当图片过大 并且 浏览器较小时，就会发生图片的头部被切掉的问题。
目前的做法：
- 当浏览器的面积（分辨率）小于`1440*900(820)`时，会设置背景为左上角对齐，这样背景至少可以显示头部。
- 在上述分辨率下，会显示一个背景位置设置的选项，（包括：左上角对齐与居中对齐）

默认情况下：
大于`1440*900(820)`时，背景居中对齐；
小于`1440*900(820)`时，背景左上对齐；

上述功能将于`1.4.3`发布。

**Comment by yang-ling** [comment]
> 另外，如果有新版本出来，请问是否想要提前体验，已帮助SimpTab发现未知Bug？、

可以呀，很乐意。

**Comment by Kenshin** [comment]
目前 `1.4.3` 已经进入 `Release` 通道，你可以 `pull` 此分支的代码，或者请告知你的`Email`地址，我把crx直接发给你。

**Comment by yang-ling** [comment]
我直接pull代码好了，有问题发issue

**Comment by Kenshin** [comment]
`1.4.3` 已经发布。在分辨率较小的时候，会显示背景位置设置选项。 :)
