### ISSUE TITLE
如何实现给新标签页加个图标？

### ISSUE THREAD

**Issue by cdchs99** [Kenshin/simptab#100]
就新标签页只有文字，看着怪难受的。

**Comment by cdchs99** [comment]
刚刚发现，可以显示输入法打出来的表情

**Comment by Kenshin** [comment]
很容易，你可以在 [自定义标题](https://simptab.art/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E9%A2%98) 查看。

高级/折腾点的方案 → 使用 `(function(){xxx})()` 就行。

**Comment by Kenshin** [comment]
嗨，我关闭这个 Issues 了，有需要你再重开它。
