### ISSUE TITLE
是否支持原生书签栏？

### ISSUE THREAD

**Issue by eallion** [Kenshin/simptab#107]
是否支持原生书签栏？
原生书签栏仅在 Newtab 页显示。正常浏览网页时不显示。我觉得这是 Chrome 最好的功能之一，希望支持一下。

**Comment by Kenshin** [comment]
谢谢建议

第三方的 New Tab 都无法支持原生的浏览器书签。😤

**Comment by eallion** [comment]
> 谢谢建议
> 
> 第三方的 New Tab 都无法支持原生的浏览器书签。

原来如此。（我也没有看过官方文档
