### ISSUE TITLE
无法下载背景

### ISSUE THREAD

**Issue by singledogliu** [Kenshin/simptab#112]
下载时控制台报错“Unchecked runtime.lastError: Invalid filename”

**Comment by Kenshin** [comment]
请问是任意一个背景都无法下载吗？

**Comment by singledogliu** [comment]
是的，我用edge和Chrome分别各尝试了三张，报错信息都一样。
![简悦报错](https://user-images.githubusercontent.com/38743306/108932456-5111b980-7641-11eb-8aa6-74eb0ee8b0b9.jpg)

**Comment by Kenshin** [comment]
emmm...

刚测试了下，是可以下载的，你可以通过背景管理器随便找一个背景，然后试试下载，另外，看看 `chrome://extensions/?id=kbgmbmkhepchmmcnbdbclpkpegbgikjc` 里面是否修改了什么配置？

**Comment by Kenshin** [comment]
还有个提示：你是否安装了某些接管浏览器的下载管理器的扩展？

也有可能是此问题引起。

**Comment by singledogliu** [comment]
在背景管理器下载失败，仅启用简悦一个扩展的情况下下载也失败了，报错信息未变，Chrome与edge情况相同，二者皆为最新版。

**Comment by Kenshin** [comment]
重新安装也无法解决吗？
如果是的话，告知你的浏览器与操作系统版本。

**Comment by singledogliu** [comment]
找到问题所在了，开启了背景源中的“自定义下载位置功能”并填写了目录地址（随便填什么目录都会报错）后无法下载，不启用该功能或启用了未填写目录地址则能正常下载。
![自定义下载位置保存](https://user-images.githubusercontent.com/38743306/109259371-f2d90800-77f3-11eb-9751-6c7f37d50522.jpg)

**Comment by singledogliu** [comment]
再一次仔细看了下关于“自定义下载位置”功能的介绍，原来是在默认下载位置中自定义文件夹，以为是可以自定义任意下载位置，之前没有仔细看理解错了，感谢作者大大这几天的回答和帮助！

**Comment by Kenshin** [comment]
> 再一次仔细看了下关于“自定义下载位置”功能的介绍，原来是在默认下载位置中自定义文件夹，以为是可以自定义任意下载位置，之前没有仔细看理解错了，感谢作者大大这几天的回答和帮助！

哈哈，么事，搞定就好，我关闭此 Issues 了。 😉
