### ISSUE TITLE
更新日志是否需要多语言？

### ISSUE THREAD

**Issue by airycanon** [Kenshin/simptab#12]
首次启动 Simptab 时，弹出版本已更新的通知，其中更新日志链接为https://github.com/kenshin/simptab/blob/master/CHANGELOG.md
目前为英文版，需要添加其他语言的版本吗？

**Comment by Kenshin** [comment]
应该需要的，以后会把更新日志放到www中，目前暂时先在github里面。

**Comment by Kenshin** [comment]
1.5.2 已更新，详细说明请看更新日志 http://ksria.com/simptab/docs/#/CHANGELOG?id=_152
更新日志的多语言已经加入，我将关闭此 issues
