### ISSUE TITLE
能否去除或是弱化背景源提醒？

### ISSUE THREAD

**Issue by Higurashi-kagome** [Kenshin/simptab#120]
很喜欢，非常感谢！

注意到在没有作其他配置时，打开新标签页会不时弹出下面的提示：

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/51501079/125152192-a2988c00-e17d-11eb-8e67-720d7d77d05f.png)

</details>

我觉得这个通知可以去掉，因为这并不是太重要的通知，更重要的是它使得 simptab 有那么点不 simple 了。

如果选择留下该通知，那么提供一个“不再提醒”选项也很好。

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简 Tab 

至于你说的问题，因为选择了「收藏夹为背景源」，然后随机切换到收藏夹但没有背景源才有的提示，你可以这样做：

![image](https://user-images.githubusercontent.com/81074/125154060-a1219080-e18a-11eb-9dbf-db22fe9ed93c.png)

**Comment by Higurashi-kagome** [comment]
的确有用，谢谢。
