### ISSUE TITLE
新的背景获取失败  

### ISSUE THREAD

**Issue by bai12123** [Kenshin/simptab#129]
作者你好。这个扩展很好用，但是我在使用过程中遇到了2个问题和1个建议，望能回复下。
1.我在设定中，勾选了如图所示选项。结果打开新标签后显示新的背景获取失败，请重新获取。我这样勾选仅仅是因为我想只从wallhaven获取背景。难道这样是无效的？
![Snipaste](https://user-images.githubusercontent.com/99849852/167282623-a4698727-6d08-4ff1-b671-137593054eb4.png)
2.常用网址，简单模式。工具栏上显示的网址不能像chrome原标签页上一样，按x删除
3.右侧详细信息按钮。点击直接跳转到了原图网址，这样反而干扰到了背景的显示。希望能改成这样：点击详细信息，弹出一个浮动半透明的窗口，窗口显示背景图片的大小，分辨率，原图网址(可点击新标签跳转）

**Comment by Kenshin** [comment]
嗨，谢谢喜欢简 Tab

> 问题1

看截图设置是没问题的，wallhaven 每次都失败吗？确保网络畅通。

> 问题2

确实没有直接编辑的功能，可以在选项里面编辑

![image](https://user-images.githubusercontent.com/81074/167284601-8271f2f1-d433-4687-bce8-5bee31cf5d0e.png)

> 问题3

可以考虑，但既然点击了，就是用户主动选择了，所以感觉似乎有些「多余」。

**Comment by bai12123** [comment]
问题1.是的。经过测试，清除浏览器数据，重装扩展，无论开不开clash，都是获取失败，还提示我当前收藏无任何背景，已自动设置默认背景。另一点，我又勾选了simptab精选集，但我并没有在背景管理器中查看精选集和探索，然后一样获取失败，去了精选集和探索，加载了几张图片，返回再刷新，显示了加载的这几张图片。感觉背景获取方式确实是有点问题。
问题3.确实是主动选择，但倘若遇到了喜欢的图片，浮窗显示信息符合要求，然后可以直接点击下载当前背景，体验会更好。

**Comment by Kenshin** [comment]
> 问题一

明天确认下，你可以暂时试试仅使用精选集是否可以改善？如果不能的话，应该是设置问题。

另外，还有个选项大概叫随机背景的选项。
> 问题三

收到，会考虑的。

**Comment by Kenshin** [comment]
我是说下图的选项

![image](https://user-images.githubusercontent.com/81074/167330851-c2361a38-2848-4f78-88b4-3a841b19c593.png)

**Comment by bai12123** [comment]
![Snipaste](https://user-images.githubusercontent.com/99849852/167333822-a0576c7e-b53b-43d5-8721-0aa7d6ac26ec.png)
这就是我一开始的设置。因为我喜欢的是简约风的图片，里面的来源都不太符合我的审美，wallhaven里的排行榜图片还不错，所以我想试试，大多用的也是收藏。但是结果发现加载不了

**Comment by bai12123** [comment]
所以这个bug什么时候可以修复呀？
