### ISSUE TITLE
請問電影劇照來自那個來源？

### ISSUE THREAD

**Issue by dfpoon** [Kenshin/simptab#13]
我不大喜歡看電影劇照，請問我應該取消那個圖片來源呢？

**Comment by Kenshin** [comment]
你好，根據反饋，下個版本中將加入電影背景源的開關選項。

* 如果允許的話，下個版本發佈時，我會Email通知你。
* 如果懂得編譯Chrome extension的話，可以pull develop分支的代碼，然後手動編譯爲crx文件。
此分支中已經加入了對電影源的控制。
* 如果着急使用的話，我可以把 develop分支的crx先發給你。

**develop的代碼非Release版本，但正常使用沒問題。**

感謝使用SimpTab。 :+1:

**Comment by Kenshin** [comment]
我已經把這個源的一些大家覺得不好看的圖片（電影海報）下架了，可以不用上面的方式。
同樣，新版本上線後，會有更多的背景源，到時我會通知你。

**Comment by dfpoon** [comment]
聖誕快樂！謝謝你的快速回應。開帖原本只因為個人不太喜歡電影海報作背景，只想找個簡單辦法剔除，並不是想這樣麻煩你。謝謝你！

**Comment by Kenshin** [comment]
沒關係的，因爲有些用戶提出過這個（電影海報）的問題，所以需要改善一下UE。

**Comment by airycanon** [comment]
随着图片源越来越丰富，总会有一些图片是用户不喜欢的，是否可以加入一个不太显眼的信息，标识当前图片来自于哪个源，这样假如用户对某个源不满意，那就可以自行禁用掉了。

**Comment by Kenshin** [comment]
電影海報已經加入到側欄中，名稱叫做"SimpTab Images"如果不想顯示電影海報等內容的話，不啟用這個源即可。（默認為不啟用）

**Comment by Kenshin** [comment]
@airycanon 
这个问题转移到 [#15](https://github.com/Kenshin/simptab/issues/15)
