### ISSUE TITLE
新版Chrome无法使用

### ISSUE THREAD

**Issue by Vstory** [Kenshin/simptab#135]
扩展还会更新吗

**Comment by Kenshin** [comment]
嗨

可以使用，请问无法使用的提示是什么？

**Comment by Vstory** [comment]
> 嗨
> 
> 可以使用，请问无法使用的提示是什么？

如图所示，扩展无效。
![image](https://github.com/user-attachments/assets/8b9ea0a4-bcab-4c1f-99f9-bd976b23edbb)
https://support.google.com/chrome_webstore/answer/2664769#unsupported_extensions

![image](https://github.com/user-attachments/assets/897f187e-2785-4723-ab42-84eace8a0e1b)

**Comment by Kenshin** [comment]
没问题，你直接安装就行，能安装就能使用，不用理会 Chrome 的说明...

![image](https://github.com/user-attachments/assets/4a48e409-f87d-42fb-b02d-f418fc30a995)

<img width="491" alt="image" src="https://github.com/user-attachments/assets/76eb3b3b-f353-4b76-8a1b-51ed92aa2b92">

<img width="1823" alt="image" src="https://github.com/user-attachments/assets/164db4a2-a668-4afd-a16b-1692a45a7263">

**Comment by Kenshin** [comment]
打开你提供的网页 https://support.google.com/chrome_webstore/answer/2664769#unsupported_extensions 下面有这样一段话。

<img width="774" alt="image" src="https://github.com/user-attachments/assets/bfa4625c-0846-471a-ba21-5a9fe2264a2d">

**Comment by Vstory** [comment]
> 打开你提供的网页 https://support.google.com/chrome_webstore/answer/2664769#unsupported_extensions 下面有这样一段话。
> 
> <img alt="image" width="774" src="https://private-user-images.githubusercontent.com/81074/365338822-bfa4625c-0846-471a-ba21-5a9fe2264a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTMzMDgsIm5iZiI6MTcyNTY5MzAwOCwicGF0aCI6Ii84MTA3NC8zNjUzMzg4MjItYmZhNDYyNWMtMDg0Ni00NzFhLWJhMjEtNWE5ZmUyMjY0YTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA3MTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZmEwN2Q5MWQ4ZDk2ZjEwNzBhMDM1ZGMzMzZkNGFkYjBhZTE2NjExOTU0ZWZkNDM2YzliZWFjY2Q2ZGFhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oiJ_JKJ98FtuOQTBYOnMPSIRpyaMRxL79NPumm8EzXQ">

没有这个选项的

**Comment by Vstory** [comment]
录制了操作视频，发送到了官网关于里的邮箱 https://simptab.art/

**Comment by Vstory** [comment]
![image](https://github.com/user-attachments/assets/9f2ff271-9296-4191-ad3d-8235261a803b)
尝试卸载重装，直接不支持安装了

开发者模式下，本地安装一样。就是不支持新版chrome
本地安装报错如下:
![image](https://github.com/user-attachments/assets/8e01c340-dabd-430a-8a85-be1c82e2d341)

**Comment by Kenshin** [comment]
嗨，我重现了这个问题，解决方案可以看下 https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575710

100% 可以解决 😂

**Comment by Vstory** [comment]
> 嗨，我重现了这个问题，解决方案可以看下 [Kenshin/simpread#6633 (comment)](https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575710)
> 
> 100% 可以解决 😂

只能安装，功能依旧无法生效

**Comment by Kenshin** [comment]
我这边没问题，因为测试过，所以才通知你的。

所以，你提到的

> 功能依旧无法生效

具体指什么？

**Comment by Vstory** [comment]
> 我这边没问题，因为测试过，所以才通知你的。
> 
> 所以，你提到的
> 
> > 功能依旧无法生效
> 
> 具体指什么？

已解决。
我记得以前点击新建标签页就是简tab，然后地址栏有个扩展图标，可能我记错了。

**Comment by Kenshin** [comment]
假设仍有问题的话，我更新了 https://github.com/Kenshin/simpread/discussions/6633#discussioncomment-10575710 的使用说明，从下图看起（与简 Tab 类似）

<img width="867" alt="image" src="https://github.com/user-attachments/assets/a9c014d8-1a25-41c5-a53d-0d6f5d9be6d7">

注意：Chrome 的这种提示仅出现一次，重启浏览器后不再提示，通过此方式安装的扩展仍可以跟随浏览器账户一起同步。
