### ISSUE TITLE
是否考虑加入自定义下载位置

### ISSUE THREAD

**Issue by zwpaper** [Kenshin/simptab#14]
在 Mac 下，我希望把下载下来的图片作为桌面背景，而每次下载图片都在能放在 Downloads 中，还得手动移动位置，比较不方便，所以希望问一下是否考虑加入自定义下载位置

**Comment by Kenshin** [comment]
之前放假了，刚刚回来。 :)
嗯，好像下载位置都是默认的，我先标记一下，回头查查！
感谢建议~

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

新增加 [自定义下载位置](https://simptab.art/docs/#/背景源?id=自定义下载位置)，解决了此问题

***

除此之外，增加了若干新功能，部分功能如下：

-  [12/24 制式转换](https://simptab.art/docs/#/选项页?id=时间)

-  [自定义标题栏](https://simptab.art/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](https://simptab.art/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](https://simptab.art/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](https://simptab.art/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](https://simptab.art/docs/#/选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
