### ISSUE TITLE
建议增加“不喜欢”功能

### ISSUE THREAD

**Issue by bj-wei** [Kenshin/simptab#15]
RT。遇到不喜欢的图片时，选择“不喜欢”，以后不再出现

**Comment by Kenshin** [comment]
之前放假了，刚刚回来。 :)
由于图片源越来越多，所以肯定会遇到这个情况，我想过这个问题，下个版本会加入此功能。
感谢建议~

**Comment by Kenshin** [comment]
`1.5.0` 已经加入不喜欢功能，并已经发布~
