### ISSUE TITLE
Top Site 统计是否算上在Top Site中点击的次数？

### ISSUE THREAD

**Issue by zwpaper** [Kenshin/simptab#16]
这是我在使用时碰到一个问题，想问一下，只能发一个issue，希望不会太打扰。

如题，如果我通过点 Top site 中的网站访问目标网站，好像并不增加它的排位，而我手动在地址栏输入的网站只输入几次，就会比我经常去的网络靠前，所以我有点好奇是不是我点 top site 时，并不增加 top site 中记录数。

**Comment by Kenshin** [comment]
没有打扰，欢迎任何疑问在这里发出，因为你的疑问或许也代表其他人。 :)
SimpTab只是自动调用Chrome extension的API，所以API给了什么内容，SimpTab就显示什么内容。
大下个版本（1.6.x）会加入定制Topsites的功能。

**Comment by zwpaper** [comment]
之前在V2听你说不加入 Top sites 定制功能还失望了一会，好消息啊

**Comment by Kenshin** [comment]
之前是因为Topsites使用的人不会很多，所以没必要增加custom功能，但后来发现太多用户喜欢这个功能，所以自然会更新下去。 :)
这个功能上线后，会优先通知你，不过，时间或许会长些，因为中间隔一个大版本的更新。

**Comment by zwpaper** [comment]
好的，也不着急~谢谢了

**Comment by Kenshin** [comment]
`1.4.3` 已经发布，但暂时没有加入你想要的Topsits定制功能。但增加了Topsites的九宫格显示。 :)

**Comment by zwpaper** [comment]
用上了~Senior Topsites，感觉比之前的好看了！

PS，顺路报个 Bug，Setting 按键的英文应该是 SETTINGS，XD
当然，我主要想说的是在 Settings 页面里，多选框点击无效，必须点文字才能选中，有点不合逻辑

**Comment by Kenshin** [comment]
嗯，多选无效是因为这个icon仅仅是装饰用的... XD
Bug先记下，回头下次升级的时候，一起发布。

**Comment by Kenshin** [comment]
这两个问题已经Fix，会跟着 `1.5.0` 时一起发布。
