### ISSUE TITLE
是否考虑增加快捷键快速打开自定义的网页

### ISSUE THREAD

**Issue by wiley7** [Kenshin/simptab#19]
提供快捷键映射，设置快捷键打开设置好的页面，比如设置
`"B"="http://www.baidu.com"`

**Comment by Kenshin** [comment]
之前的确考虑过，但有个问题。当 `New Tab` 打开时，是没有 `焦点` 的情况，所以快捷键无法使用。要实现这个功能的话，需要让 `New Tab` 处于焦点状态（比如鼠标点击）。
这样的话，体验性太差，所以就暂时没有实现。
而Chrome extensions只能绑定4个快捷键。

如果你有好的办法，可以分享一下~

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，增加了 [自定义常用网址](http://ksria.com/simptab/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E7%AB%99%E7%82%B9) 的功能，以及对应的快捷键支持。

***
简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
