### ISSUE TITLE
大屏幕下的图源问题

### ISSUE THREAD

**Issue by skys215** [Kenshin/simptab#20]
你好。
我在next.36kr.com上看到别人推荐你的插件，非常喜欢。
但是我在使用的过程中发现一个问题。
因为我使用的是21:9超宽屏幕，而背景图片素材通常没那么大，
一经屏幕宽度等比缩放，背景图片就不好看了。
例如只能看到灯塔头部，建筑物顶部之类的。

如果能设置成，根据窗口宽度、高度，或者屏幕宽度和高度来下载相应的图片，
则我认为会好很多。

谢谢。

**Comment by Kenshin** [comment]
感谢提建议 :)
首先，这是个 **已知** 的 `bug`，没想好如何修复。

我也是大屏，但我一般情况下 `Chrome` 都只用一半来显示。因为绝大多数网站都没有适配这种分辨率。

通常下，网站遇到像这种分辨率的话，居中就行了，顶多两边有白边，但这个规则不太适用于背景。如果背景居中的话，两边会非常难看...
`unsplash.it` `unsplash.com` 这两个源的大尺寸的背景比较多。
PS：如果你有更好的想法，希望分享一下 :)

**Comment by skys215** [comment]
居中的情况下，两边的白边用背景的毛玻璃效果填充如何？（只是yy而已，不保证会好看

另外，我随便找了找大分辨率的图源。不知道方不方便开发/应用（有的API可能会有次数或频率限制）
[Pexel](https://www.pexels.com/api/)和[Pixabay](https://pixabay.com/api/docs/)
（我的另外一台电脑里面有几个高清图片的网站，今晚回去看一下并确认一下有没有API）

**Comment by Kenshin** [comment]
okay，我试试你说的情况。先不管是否好看，但毛玻璃效果比较耗内存。 :( 
假设有高清的背景源是最好了。3ks~

**Comment by skys215** [comment]
我看了一下几个我收藏的网站，
分别是[WallHaven](http://alpha.wallhaven.cc/)，[WallpapersCraft](https://wallpaperscraft.com/)
不过都没有提供API。伤心😢

**Comment by Kenshin** [comment]
没事，没有API也行，如果有规律的话，我手动抓取，感谢你了。 :)
我想想有没有什么更好的办法解决这个问题。

**Comment by skys215** [comment]
http://www.polayoutu.com/collections
CC0协议的图源。
话说，开个贴让大家贡献图源如何？（虽然新tab有上传图片的入口……

**Comment by Kenshin** [comment]
cool~
你觉得现在的图源 还不够多吗？或者说有些源的质量不高？
增加图源本没什么问题，但是如果给太多的选择，万一有选择性障碍呢 哈哈~

**Comment by skys215** [comment]
现在图源是够的，只是大屏幕的时候，图片会被裁掉。
像500px的有水印，缩小窗口的时候，就显示个00px在背景上，就感觉不好看了。

我个人认为不会有人去挑图源吧？要不全勾上，要不只勾自己想看的。 “啊~今天想看这个图源，明天想看这个图源” 这种需求我觉得应该没有。

增加图源是为了满足多种屏幕比例。
（不知道插件在下载图片的时候有没有考虑屏幕比例的问题）
你觉得如何呢？

**Comment by Kenshin** [comment]
嗯，现在的问题是 `如何能解决大屏幕图源` ，我这两天在考虑一个方案，等这几天有时间的时候，测试一下，如果可行的话，咱们在讨论 具体需求的情况。
不过，稍微有些麻烦...

**Comment by skys215** [comment]
好的~
静候佳音。

**Comment by Kenshin** [comment]
嗨，久等了！

1.5.1 已经发布！

新增加的【相框效果】可以解决大屏幕下背景源不好看的问题，详细请看 [更新日志](https://github.com/Kenshin/simptab/blob/master/CHANGELOG.md#151)
