### ISSUE TITLE
在窄屏幕下时间显示不全的问题

### ISSUE THREAD

**Issue by skys215** [Kenshin/simptab#21]
![image](https://cloud.githubusercontent.com/assets/4977935/13721542/92028218-e865-11e5-83fa-fe778fbfc529.png)
我的屏幕是1366*768, 打开新窗口时时间只显示一半。
（我在大屏浏览器下也有同步同一帐号，或许是这个原因？

**Comment by Kenshin** [comment]
在大屏下应该没有问题吧？

**Comment by skys215** [comment]
大屏下没问题。
但是1366*768属于常见分辨率吧？
我个人认为应该支持一下的……

**Comment by Kenshin** [comment]
`1366*768` 其实应该已经支持了...你可以看到侧栏有个关于背景位置的选项，这就是专门为小屏设计的。
你的问题比较奇怪，目测这种情况应该是浏览器的底边超过了屏幕的下方造成的...
我在同样分辨率下没有发现，回头找个小屏，再试试！
感谢反馈~

**Comment by Kenshin** [comment]
嗨，久等了！

1.5.1 已经发布！

新增加了一个【相框布局】，可以解决任意尺寸浏览器显示不全的问题，详细请看 [更新日志](https://github.com/Kenshin/simptab/blob/master/CHANGELOG.md#151)
