### ISSUE TITLE
使用simptab设置chrome的常用标签页

### ISSUE THREAD

**Issue by saccohuo** [Kenshin/simptab#22]
怎么使用simptab设置chrome的那几个常用标签页呢？包括添加和删除。

**Comment by Kenshin** [comment]
`常用网址（ Topsites ）` 暂时没有自定义功能，这些数据直接来自 `Chrome` 。
如果需求较多的话，下个版本会实现它。 :)

**Comment by saccohuo** [comment]
@Kenshin 嗯，差不多就是speed dial的功能

**Comment by Kenshin** [comment]
1.5.2 已更新，增加了 `书签栏`，详细说明请看更新日志 http://ksria.com/simptab/docs/#/CHANGELOG?id=_152

我将关闭这个 issues ~
