### ISSUE TITLE
关于书签栏和搜索栏

### ISSUE THREAD

**Issue by StrollStars** [Kenshin/simptab#23]
1.书签栏可否跟默认新标签页一样，显示在地址栏下方，就如[Infinity新标签页](https://chrome.google.com/webstore/detail/infinity-new-tab/dbfmnekepjoapopniengjbcpnbljalfg)扩展实现的那样。
2.搜索栏输入命令好像没什么效果。
PS：二十四节气怎么显示的？

**Comment by Kenshin** [comment]
1. 这点在实现上没问题，只是需要看大家是否需要这个功能点。 :) 另外，放到上面的理由是什么？当然，如果理由充足的话，哪怕只有一个人提出，我也会实现它。
2. 你觉得哪个命令没效果？是无法激活搜索栏？还是其它情况？
3. 二十四节气 是手动设置的，这几天可能有点忙...忘记新的节气了 :sweat:

**Comment by StrollStars** [comment]
1.Chrome提供了“总是显示书签栏”的设置项，如果选中则一直停留在上方，如果点击则在当前页打开，如果当前页还需浏览则会被打断。如果当前页确实没用，那么个人以为关闭再新开标签页更合适，在历史中查询也是每个站点一条记录，也便于进程的资源回收，这样就适合不选中“总是显示书签栏”的设置项了。但若在新标签页中也没有了书签栏，那么通过书签管理器去打开书签，不仅操作繁琐，而且也不够直观。如果我的习惯比较小众，可否设置选项，可显示或者隐藏书签栏呢？
2.现在就应用感觉是正常的，其他都是“未找到此网页”或没有反映。另，这个命令只要在地址栏执行就可以了，不一定要在新标签页吧？
3.我是不知道该怎么用，没试出来。
谢谢您的开发，慢工出细活。^_^

**Comment by Kenshin** [comment]
感谢这么详细的解释。 :+1: 
1. 如果隐藏了书签栏，在 `SimpTab` 的新标签页是无法看到的，目前 `SimpTab` 只提供了 `经常使用的网址` 的功能。我会考虑实现书签栏的功能，虽然到目前没人提出来，但毕竟是个实用性的功能。
2. 如你所述，这个命令在任意页面的地址栏中激活（ `ST` ）就可以使用。但在非 `New Tab` 中激活的话，只能使用 `常用网址` 的功能。

**Comment by StrollStars** [comment]
1.非常感谢采纳建议，期待新版。提供隐藏选项是兼顾一些喜欢现在样子的用户，我想有了这个之后一般人都不会隐藏吧。
2.原来如此。
3.历史功能改成设定那样右侧划出可能更好些，不过第一条优先了。

**Comment by Kenshin** [comment]
`历史功能` 暂时只能先这样。 :)
`书签栏功能` 新版上线后，我会手动 AT 你。

**Comment by StrollStars** [comment]
再次感谢^_^

**Comment by Kenshin** [comment]
1.5.2 已更新，增加了 `书签栏`，详细说明请看更新日志 http://ksria.com/simptab/docs/#/CHANGELOG?id=_152

我将关闭这个 issues

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，在 `快捷键搜索栏` 中增加了此功能，详细请看 [自定义搜索](http://ksria.com/simptab/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%90%9C%E7%B4%A2)

***
PS：简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
