### ISSUE TITLE
mac os下安装的时候，直接用户被登出

### ISSUE THREAD

**Issue by zhuzhe1983** [Kenshin/simptab#24]
mac os下安装的时候，直接用户被登出，这是什么原因。。。

**Comment by Kenshin** [comment]
用户被踢出？什么意思？

**Comment by zhuzhe1983** [comment]
当前系统登录用户被注销，登出

2016年5月12日星期四，kenshin <notifications@github.com> 写道：

**Comment by Kenshin** [comment]
你是说 `Chrome` 登录的账户被踢出？截个图 或者 录屏 都行。
你的 `Chrome` 是什么版本？第三方？还是原生？
这个插件就是在 ` MAC` 上开发的，而且 `Chrome` 的安全机制比较高，`extension` 都运行在 `sandbox` 里，不应该对 Chrome 造成任何影响...

**Comment by zhuzhe1983** [comment]
Mac OS的用户被登出，我回头查下系统日志吧。

2016年5月13日星期五，kenshin <notifications@github.com> 写道：

**Comment by Kenshin** [comment]
okay，我在找其他人问问。

**Comment by Kenshin** [comment]
请看截图
![Imgur](http://i.imgur.com/FsgVnrO.jpg)
现在还有这个问题吗？
