### ISSUE TITLE
请问在哪能找到我收藏过的壁纸

### ISSUE THREAD

**Issue by litaiming** [Kenshin/simptab#26]

**Comment by Kenshin** [comment]
感谢使用~
`SimpTab` 的收藏功能会把背景保存到 Chrome extensions 的沙箱里面，路径类似 `filesystem:chrome-extension://kbgmbmkhepchmmcnbdbclpkpegbgikjc/temporary/20160420101645.jpg` 这样的位置。
目前的版本暂时未提供管理及导出功能，下个版本会提供。 :)
