### ISSUE TITLE
请问能否一直使用自己设置好的背景？

### ISSUE THREAD

**Issue by JulyFinal** [Kenshin/simptab#27]
当选择一天一换的时候，无法上传图片，但是当选择随机的话，虽然可以上传，但是每次启动都会换一次，有什么办法可以保持一个图片不变吗？

**Comment by Kenshin** [comment]
SimpTab 的设计理念没有这种功能，但可以使用 `Pin` 功能，最多只能 `Pin` 8小时。 :)

**Comment by JulyFinal** [comment]
原来如此，很新颖，我会慢慢习惯的 :)
（如果有可能的话还是非常希望有一个这样的功能^_^）
非常喜欢您这个作品希望越做越好。

**Comment by Kenshin** [comment]
如果只是单一背景的话，有悖 `SimpTab` 设计初衷，但我会考虑你的建议。
感谢使用，希望 `SimpTab` 给你带来好心情。 :)
