### ISSUE TITLE
能不能加一个google搜索框

### ISSUE THREAD

**Issue by ritianxia** [Kenshin/simptab#28]

**Comment by Kenshin** [comment]
感谢建议。
之前在做 `SimpTab` 时就定下一个目标：极简；因此 `SimpTab` 只关注标签页背景的呈现方式。 
Chrome 本身的搜索功能很强大了，如果有需要的话，可以利用它自身的搜索（地址栏），所以 `SimpTab` 没必要再重新做一个搜索。
虽然其它很多类似的 `New Tab` 产品都有自己的搜索，但这并不是 `SimpTab` 的初衷。 :)

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，在 `快捷键搜索栏` 中增加了此功能，详细请看 [自定义搜索](http://ksria.com/simptab/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%90%9C%E7%B4%A2)

***
PS：简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
