### ISSUE TITLE
安装了Toby之后new tab被它接管了

### ISSUE THREAD

**Issue by xilin** [Kenshin/simptab#29]
有什么办法可以设置成simptab优先不？

**Comment by Kenshin** [comment]
目前没有办法... 因为它们都属于 `New Tab` ，你可以先选中 `Toby` 然后再选中 `SimpTab` ，它就能回来了，但 `Toby` 就不好使了。

**Comment by xilin** [comment]
@Kenshin Toby我只需要点图标能出现就行
不过你说的操作步骤是在哪进行的呢？我试过在extensions里先禁用simptab再开启也不行

**Comment by Kenshin** [comment]
哦，我刚刚试了试，似乎不行！
目前只能二选一...

**Comment by xilin** [comment]
好的，谢谢！

**Comment by Kenshin** [comment]
近期有准备实现一个类似 `Toby` 的 插件，有兴趣的话，到时候有内测版本可以发给你。 :)
PS：如果不介意的话，可以说说喜欢 `Toby` 哪几个功能？

**Comment by xilin** [comment]
如果能和simptab结合起来就最好啦
用Toby主要是用来当read it later用，可以管理标签页，分组，设备同步

**Comment by Kenshin** [comment]
它们的设计初衷（定位）不一样，如果是我来做的话，肯定不会占用 `New Tab` 的位置，并不是因为已经有了  `SimpTab` ，而是本身它们的定位不一样，没必要放到一起。
这两天在试用  `Toby` ，发现它本身有些 `问题` ，所以才打算自己撸一个。 :)

**Comment by xilin** [comment]
是的，我原来用OneTab觉得也不错，就是UI不如Toby

**Comment by numbero** [comment]
我也遇到了相同的问题，但在最新版的toby中，其设置页面会提示“如果不希望占用新标签页面，请尝试toby lite”，此处的toby lite是删去了新标签页面的精简版，完美适应既可以使用toby的主要功能而且不会占用新标签页的需求

**Comment by Kenshin** [comment]
> 我也遇到了相同的问题，但在最新版的toby中，其设置页面会提示“如果不希望占用新标签页面，请尝试toby lite”，此处的toby lite是删去了新标签页面的精简版，完美适应既可以使用toby的主要功能而且不会占用新标签页的需求

@Numbero 

哈哈，这是一个 17 年的 Issues，吓我一跳，诈尸了。 😂

**Comment by Zss1990** [comment]
使用 Toby 可以试下 Toby Mini，不占用 new tab

**Comment by godefy** [comment]
我换了 Toby Mini，一开始不会占用新页签，过了几天，新页签又变成toby页面了。而且奇怪的是我在公司电脑就能正常，在家里电脑就变成toby页面优先。

**Comment by Kenshin** [comment]
@godefy 

估计还是设置的问题？ 😂 

PS：好久不用 Toby 了~
