### ISSUE TITLE
图片已经很久没有换过了..一直就是一张图片，如何解决啊

### ISSUE THREAD

**Issue by xwx617** [Kenshin/simptab#30]
我没有固定背景，甚至还点了不喜欢但还是没有用

**Comment by Kenshin** [comment]
侧栏里面的图片源选取了吗？是不是不能科学上网，因为有些图片源就会加载很慢。
另外，每日更新 `Bing.com` 背景的功能好使吗？

**Comment by xwx617** [comment]
已经解决了，突然间不知道为什么又好了，感觉可能是我网络的问题，我全程挂着ss的

**Comment by Kenshin** [comment]
okay，`New Tab` 左下角有个加载的 `loading bar` 当正确加载后，会显示完成 `loading` 的效果，你下次留意一下。这样可以排除是否时网络问题导致。

**Comment by Kenshin** [comment]
1.5.1 已经发布，解决了上述各种问题，详细请看 [更新日志](https://github.com/Kenshin/simptab/blob/master/CHANGELOG.md#151)
