### ISSUE TITLE
近来更新图片非常慢，甚至无法更新图片。

### ISSUE THREAD

**Issue by cryschao** [Kenshin/simptab#31]
左下角的进度条，从0到一个固定的位置后，卡住，然后消失了。。。
讲道理，应该不是我网络问题。

不知道其他人有碰到吗？老板抽空帮忙解惑一下。

**Comment by Kenshin** [comment]
我没有遇到这个问题，背景源有一些跟科学上网有关。
给你一个排除法：
把全部的背景墙都取消（即：默认只下载 bing.com 的背景），然后刷新新标签页，看看左下角能否正常完成以及背景是否能更新。

**Comment by cryschao** [comment]
![tim 20170802005410](https://user-images.githubusercontent.com/3120362/28836879-4bef0a60-771d-11e7-868e-c505a36121f0.png)
![tim 20170802005437](https://user-images.githubusercontent.com/3120362/28836880-4bf3ac78-771d-11e7-99fc-a82eba7e5108.png)

按你的方法排除了，还是一样，而且科学上网也没问题，用的是xx-net。奇怪``

**Comment by Kenshin** [comment]
@cryschao 
请问你的每日 Bing 背景更新有问题吗？
当未加载完时（第二幅图），你可以看看 Chrome Developer Tools - Console 里面有没有什么报错。

假设排除掉上述两个问题后，你可以安装 `非 Chrome webstore 版`，并在 `chrome://extensions` 勾掉  Chrome webstore 版，看看 `非 Chrome webstore 版` 是否也有这个问题。

另外，请告知你的 OS 及 Chrome 版本。

**Comment by cryschao** [comment]
@Kenshin 先感谢耐心解答哈。
每日Bing更新背景没问题。会更新。
报错信息我贴图，但是貌似是警告。
我去尝试下载非商店版。

先报告一下我的信息：
OS：Win10 64位 企业版
Chrome：版本 60.0.3112.78（正式版本） （64 位）


![image](https://user-images.githubusercontent.com/3120362/28856688-439ba468-7777-11e7-82e2-fd471dcf12b9.png)

**Comment by cryschao** [comment]
离线版，也是一样的卡住了。
![image](https://user-images.githubusercontent.com/3120362/28856983-b2e296dc-7778-11e7-80c0-7e0fef11162f.png)

**Comment by Kenshin** [comment]
@cryschao 
作为 `简 Tab` 的作者这是应该的，毕竟这个问题给你造成了一定的困扰。

你可以把截图中第一段的内容展开，看看有没有什么 `背景源 的 url`。

**Comment by cryschao** [comment]
离线版的截图~~ 看看有没有什么线索。貌似`bing`的那个`url`是获取图片的地址，我直接访问是到bing的首页。

![image](https://user-images.githubusercontent.com/3120362/28861071-d7c4bbd8-7791-11e7-8bf4-7f9f896189b9.png)

**Comment by Kenshin** [comment]
电脑不在旁边，明天我再看下，好奇怪的问题…
明天我给你一些 URL ，你看看能否直接访问。

**Comment by Kenshin** [comment]
@cryschao 
不好意思，昨天有些忙，我现在给出几个 url，请确认是否能成功访问。

- https://farm8.staticflickr.com/7698/26836459983_b6aa2e0bf5_h.jpg
- https://unsplash.com/photos/2MHwEybkOcw/download
- https://alpha.wallhaven.cc/wallpapers/full/wallhaven-115637.jpg
- https://unsplash.it/1920/1080/?image=319
- https://visualhunt.com/photos/xl/1/watering-water-ski-reflections.jpg
- http://lh4.ggpht.com/S-kwvQHmwhv1bhn4YJNvUWrpBQD_2Q9BEVoVXjdx3qXs1EtTr5At95W6kWlE=s1200-rw
- http://a.desktopprassets.com/wallpapers/cac8c6e8700eb017825c91fe741096e0a8ba0cbf/darkskies_tracymhymas8.jpg
- https://drscdn.500px.org/photo/222312915/m%3D1600_k%3D1_a%3D1/v2?client_application_id=16315&webp=true&sig=c98ede16a37f22ac3417cf3631aaaafc26fa8e01ad71a7dccf2a5a6b6da841f4

这几幅图基本上涵盖了 `简 Tab` 的背景源。

**Comment by cryschao** [comment]
全部可以~@ @Kenshin

**Comment by cryschao** [comment]
我测试了，全部可以。
不过我刚刚把其他图片源勾起来，是可以更换图片了。
如果全部不勾选，会出现之前的错误。
是不是不勾选其他图片源，就取不到之前`bing`的图片，然后才报的错？

**Comment by cryschao** [comment]
@Kenshin

**Comment by Kenshin** [comment]
@cryschao 
虽然解决了这个问题...

但这更奇怪了... 关闭它们意味着只加载 Bing.com 的图片；你试着访问

http://www.bing.com/az/hprichbg/rb/Umbrella_ZH-CN8238029705_1920x1080.jpg

看看能否成功，理论上 Bing.coｍ 的图片不可能无法加载才对。

**Comment by cryschao** [comment]
@Kenshin 不好意思，没留意这个问题了。

你的这个链接的bing的图可以打开，没问题。

我勾选掉其他所有的，只加载`bing`的图，`bing`的图我是每天一更新，是没问题的，但是一更新以后，再开`newtab`就会出现上面的情况。
你自己测试会吗？

**Comment by cryschao** [comment]
我看出错信息里面，请求的url并不是类似你给的.jpg结尾的URL，而是：`http://www.bing.com/gallery/home/imagedetails/53` 这样的URL，这个URL我是无法打开的，直接跳转首页。

**Comment by Kenshin** [comment]
okay，我一会看下~

**Comment by Kenshin** [comment]
@cryschao 
刚刚看了一下，是 Bing.com 调整了 `它的历史每日图片` 的 URL 地址，所以才失效造成的。

目前只有升级 `简 Tab` 才能彻底解决，临时的解决办法是把全部的背景源都打开，这样失效的机率会降低很多。

给你造成了困扰，很感谢你一直在使用简 Tab ！

**Comment by zhishanggao** [comment]
所以说,更新了吗版本

**Comment by Kenshin** [comment]
@zhishanggao 
抱歉，还未更新。😢

**Comment by Kenshin** [comment]
1.5.1 已经发布，解决了上述各种问题，详细请看 [更新日志](https://github.com/Kenshin/simptab/blob/master/CHANGELOG.md#151)
