### ISSUE TITLE
是否考虑加入固定背景无限时间选项

### ISSUE THREAD

**Issue by SUNJINZE** [Kenshin/simptab#32]
你好作者

看些背景好看 希望能够看腻了再换  不然怀念

也许已经有了，刚开始使用本插件不知道  希望解答 谢谢

**Comment by Kenshin** [comment]
感谢建议~
有 Pin 功能，最长为 8 小时，但的确没有一直固定的功能。（因为跟 SimpTab 的初衷不一样。）
会考虑这个功能。
另外，由于 Bing.com 的 API 调整，所以每日新图暂时看不到了，但不影响其它背景源。

PS：等 [简悦 ( SimpRead )](https://github.com/Kenshin/simpread) 告一段落后，我会更新 SimpTab 的。

**Comment by SUNJINZE** [comment]
嗯 谢谢！

**Comment by Kenshin** [comment]
额，忘记说了，简 Tab 1.5.2 已经支持此功能了，所以我将关闭这个 issues ~

**Comment by SUNJINZE** [comment]
> 额，忘记说了，简Tab 1.5.2已经支持此功能了，所以我将关闭这个问题〜

已经发现此功能了
感谢！
