### ISSUE TITLE
希望在新建标签页显示背景图时同时可以显示书签栏

### ISSUE THREAD

**Issue by huilaoda** [Kenshin/simptab#36]
希望增加这个配置选项，不用每次点击旁边的书签

**Comment by Kenshin** [comment]
虽然我都是显示书签栏的，但确实有些不方便。
我在筹划 1.5.2 新版，在考虑如何更好的实现这个功能。

**Comment by hakulamatatahome** [comment]
今天用这个扩展，确实挺赞，就是书签栏 没有挺麻烦的。我现在就是一直显示书签栏，可是就把浏览器的可视化空间弄小了。还是在新建标签页显示书签栏吧

**Comment by Kenshin** [comment]
1.5.2 已更新，解决了这个问题，详细说明请看更新日志 http://ksria.com/simptab/docs/#/CHANGELOG?id=_152

我将关闭此 issues
