### ISSUE TITLE
书签栏过多无法显示

### ISSUE THREAD

**Issue by ennnnny** [Kenshin/simptab#40]
如果书签栏一级太多内容，超过屏幕大小，会出现无法滚动下拉到该位置，显示不全。

**Comment by Kenshin** [comment]
下个版本会加个滚动条... 我都不用 bookmarks 要不是太多人反映，我也不会加这个功能。  😂

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，修复了此问题。

***
简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
