### ISSUE TITLE
只显示收藏夹背景，但收藏夹里什么都没有就连侧边也显示不出来的，白白的一片

### ISSUE THREAD

**Issue by s5s5** [Kenshin/simptab#41]
另：希望加入设置电脑内某个文件夹里照片为背景功能，就是自动检测某文件夹，不能总是去上传背景
另2：王者荣耀背景好多，能加上吧 https://pvp.qq.com/web201605/wallpaper.shtml

**Comment by Kenshin** [comment]
- 这是一个 Bug  ，我先记下它，由于没有做 `边界检测` 造成的，但很少有这种情况出现的。
- Chrome 对安全性有要求，无法实现你说的这种方式。
- 《王者荣耀》并不打算在 `SimpTab 精选集` 中。 😀

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，修复了此问题。

***
简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
