### ISSUE TITLE
常用网址能否考虑设置他固定显示出来

### ISSUE THREAD

**Issue by mkanako** [Kenshin/simptab#43]
因为常用网址是我使用频率极高的地方

**Comment by Kenshin** [comment]
只要「遮挡」背景图的功能都不太会实现，简 Tab 只做一件事：呈现美景~

加入 Bookmarks Topistes Clock 也都是在不遮挡的前提下完成的。

PS：可以考虑将快捷键加入到这些模块里面，或者将 Qick bar 也加入 Topsites

***
我能理解一些用户的诉求，高效 和 美景 总要找个平衡~

**Comment by mkanako** [comment]
@Kenshin 嗯，明白你对这作品有自己的定位。对我来说一张背景图+常用网址就够了，其他功能无所谓，之前一直是默认的标签页，v站看到这个有背景图试用了下，挺好，就是常用网址这个地方让我比较蛋疼。。。想哪天闲得蛋疼自己也来造个😂

**Comment by Kenshin** [comment]
其实我可以考虑加入自定义样式的功能，将更大限度的放开界面的定制化~

**Comment by mkanako** [comment]
@Kenshin 我感觉似乎自定义样式没太大必要，毕竟界面挺简单的，一张背景图而已，没什么好折腾的，也不想折腾他。
增加个选项：是/否固定显示常用网址，才是我想要的😎

**Comment by Kenshin** [comment]
可以理解~
不过，是否考虑过这种情况：B 用户觉得 底栏 的高度应该高一些，颜色应该浅一些。（其实大多数个性化要求都跟界面 · 显示 · 布局 等有关）

所以，不太可能为了任意用户的任意需求去改变之前的策略。
目前能想到最好的办法是：定制化~

**Comment by mkanako** [comment]
哦，刚试了下，通过覆盖修改样式能实现我固定显示常用网址的要求，可以~~😁

**Comment by Kenshin** [comment]
之前做 [简悦](http://ksria.com/simptab/) 时就有关于个性化的大量诉求，最后也是用这种办法解决的。

在坚持产品路线不变的前提下，一般情况只有：

- 用户提出的 Bug；
- 用户的个性化诉求；
- 用户提出的新需求；

这三种情况比较常见。

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，增加了自定义样式的功能，即可满足你的需求，详细请看 [选项页 · 自定义样式](http://ksria.com/simptab/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

***
简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
