### ISSUE TITLE
“固定”下面的那个哭脸无法点击

### ISSUE THREAD

**Issue by AoneWildernessWolf** [Kenshin/simptab#46]
移动到哭脸处时，右侧边栏都消失，轻微移动也弄不出。一开始以为常用网址遮住了，关闭后还是不行，然后才发现鼠标移动到那里时，右侧边栏就会消失

**Comment by Kenshin** [comment]
可能是分辨率造成的问题，我先记录 Bug 请问你的分辨率是多大？Chrome 发送问题时的尺寸是多少？（比如：最大化窗口等等。

**Comment by AoneWildernessWolf** [comment]
电脑官网上的写的是1366*768，任务栏在右侧。出现问题是在最大化
没有最大化窗口，发现侧边栏显示不完全。截图：https://share.weiyun.com/5gAf5ru

**Comment by Kenshin** [comment]
emmm 应该是分辨率造成的。
目前出现问题的分辨率大多在 `1366*768` ，谢谢反馈~

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，优化了 Controlbar 的 icon 布局，所以这个问题应该解决了。

***
简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
