### ISSUE TITLE
建议可以增加一个搜索框的功能。

### ISSUE THREAD

**Issue by Nomad-P** [Kenshin/simptab#47]
在newTab中搜索应该是最常用的功能吧，要是能加一个透明的搜索框功能就好了，不影响图片视觉效果的同时，可以选择使用Baidu、Google等搜索引擎，应该这个插件的使用人数会更多。

**Comment by Kenshin** [comment]
谢谢建议~

其实，Chrome 的地址栏已经很强大了，而且当你新打开一个 New Tab 时，默认光标就是在地址栏处，所以对于键盘党来说，直接输入就可以直达。（因此我不太想加入此功能，因为跟 omnibox 重叠了  😉 

PS：会考虑在 Quick bar 加入对 搜索引擎的支持~

**Comment by Nomad-P** [comment]
哦，蟹蟹提醒哈，我也用地址栏的搜索，但是平时还真的没有注意过默认光标实在地址栏哈。
优秀！

**Comment by Kenshin** [comment]
小提示：地址栏 → `chrome://flags/` 会得到隐藏技能，尤其是关于 omnibox 的！开启你感兴趣的选项后，将会得到一个无比强大的搜索提示~

**Comment by Kenshin** [comment]
简 Tab [1.5.3](http://ksria.com/simptab/docs/#/CHANGELOG) 已发布，在 快捷键搜索栏中增加了此功能，详细请看 [自定义搜索](http://ksria.com/simptab/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%90%9C%E7%B4%A2)

***
PS：简 Tab 1.5.3 最重要的一个功能是 [禅模式](http://ksria.com/simptab/docs/#/禅模式) ，适合喜欢纯色背景的用户。
