### ISSUE TITLE
当前显示的背景与详细信息中的的名称不匹配

### ISSUE THREAD

**Issue by airycanon** [Kenshin/simptab#5]
举个栗子，当前显示的是1.jpg，但详细信息和下载的tip是2.jpg，此时下载到本地的也是2.jpg，在出现这个问题时我的网络不太好，猜测是不是这个问题导致图片加载失败？

**Comment by airycanon** [comment]
把问题关了，后面发现新情况再反馈。

**Comment by Kenshin** [comment]
近期上线一个新版本，已经进入release阶段。（当然，如果你留意的话，会在github的branch发现踪迹。）如有兴趣的话，我把release版本（用你github上面的邮箱）先发给你。

**Comment by airycanon** [comment]
太感谢了，我一直在关注，上周已经把release/1.4.0分支用开发者模式导入了，目前运行良好，还在学习代码中，期待优先体验版。:)
