### ISSUE TITLE
chrome 无痕浏览模式下，右侧的滚动条呢？

### ISSUE THREAD

**Issue by waihoyu** [Kenshin/simptab#50]
chrome 无痕浏览模式下，右侧的滚动条呢？

chrome  在正常浏览模式下，右侧滚动条会出现，但是无痕浏览模式下，右侧的滚动条没有出现。

**Comment by Kenshin** [comment]
隐身模式下可以用 New Tab ？请问什么浏览器？

**Comment by waihoyu** [comment]
嗯。我之前以为是插件的问题。我重新试了一下，应该是个别网站的问题。凤凰网、网易网站在chrome 无痕浏览模式下表现正常。
结论：跟插件无关，是个别网站设计问题。

**Comment by Kenshin** [comment]
你说的是 `简悦` 吧？这里是 `简 Tab` 的 issues...
