### ISSUE TITLE
禅模式取消的问题

### ISSUE THREAD

**Issue by XinArkh** [Kenshin/simptab#51]
进入禅模式之后习惯性唤出右侧设置栏失败，找了好久才发现右下角有一个隐秘的小齿轮。
可以考虑一下在进入禅模式时增加一个退出方式的提醒，也可以在说明文档中多提一下。

这个插件用了这么久竟然还有更新，说实话挺惊喜的，支持一下，加油~

**Comment by Kenshin** [comment]
😄 确实有这个困惑，抱歉~ 禅模式的退出确实有些不好找，并且也没有做明确说明。
其实我也有描述这个功能  http://ksria.com/simptab/docs/#/禅模式?id=退出

另外，也可以使用快捷键 `c` 显示选项页。

**Comment by Kenshin** [comment]
已升级为 1.5.3.1127 （静默更新，不会有任何提示） 
增加了进入禅模式的提示（可关闭）
谢谢最初的反馈！
