### ISSUE TITLE
好棒的应用，请问可以添加一个Todo list的功能吗？

### ISSUE THREAD

**Issue by echo-ray** [Kenshin/simptab#54]
今天才发现这个这么漂亮的应用，太棒了了！

感谢您～

提个小小的请求，如果可以在新tab页面集成todo list功能，就更赞了！
 ：）

**Comment by Kenshin** [comment]
谢谢喜欢~

目前 简 Tab 有两种模式

- 纯色背景模式（即：禅模式）；
- 图片背景模式；

未来可能会 [禅模式](http://ksria.com/simptab/docs/#/禅模式) 中增加此功能~

**Comment by echo-ray** [comment]
抱歉今天才看到您的回复，
禅模式给了我更大的惊喜～！
可以提供适当的信息但是又非常简洁，完全无干扰
期待您更有空的时候添上 Todo的Feature

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

增加了 [禅模式 · 脚本管理器](https://simptab.art/docs/#/禅模式?id=脚本管理器) 里面有关于 TODO 的脚本，你可以随时切换和使用。

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](https://simptab.art/docs/#/选项页?id=时间)

-  [自定义标题栏](https://simptab.art/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](https://simptab.art/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](https://simptab.art/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](https://simptab.art/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](https://simptab.art/docs/#/选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
