### ISSUE TITLE
使用地球每刻，更换背景的提示可以选择关闭

### ISSUE THREAD

**Issue by lic2870** [Kenshin/simptab#59]
使用地球每刻，每次更换背景时，都会提示正在获取。
但是这个提示看多了就觉得有点烦人，打扰到我了。

我希望能安静地在后台静默更新，不打扰到我。
功能实现也有很多可能性，看您觉得怎么处理更合适。比如：

1. 直接去掉更新提示，只保留错误的提示。
2. 在选项里增加开关按钮。

**Comment by Kenshin** [comment]
可以改为提示并几秒后消失。

目前这么做的原因：加载地球每刻会耗时较多，所以需要让用户知道。

没必要为此增加个选项，但确如你说的，有些打扰用户。

你那里加载过长的原因估计还是网络导致的。 😄

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，解决了此问题，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

现在的方式：只有从其它模式 → 地球每刻 时才有提示，当已在 地球每刻 模式下，不会有任何提示。

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](选项页?id=时间)

-  [自定义标题栏](选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](控制栏?id=全屏化)

-  [自定义下载文件夹](背景源?id=自定义下载位置)

-  [全局性自定义脚本](选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
