### ISSUE TITLE
按b的时候，报错。啥情况

### ISSUE THREAD

**Issue by pengfd** [Kenshin/simptab#60]
![image](https://user-images.githubusercontent.com/41945423/50957293-d638c380-14f8-11e9-93b2-0c559c9c4391.png)

**Comment by Kenshin** [comment]
这是发送到手机的功能，详细说明请看 [开发文档](http://ksria.com/simptab/docs/#/%E5%8F%91%E9%80%81%E5%88%B0%E6%89%8B%E6%9C%BA)

**Comment by Kenshin** [comment]
嗨，我已修复此问题，请升级到最新版 1.5.4.202 即可解决。

我将关闭此 issues ~
