### ISSUE TITLE
希望添加 dark 主题

### ISSUE THREAD

**Issue by winwangqi** [Kenshin/simptab#62]
希望添加 dark 主题，即在新建 tab 栏，图片加载出来之前背景是黑色的。我将 chrome 的主题设置为了黑色，在新建 tab 图片加载出来之前时，背景为白色的，在晚上使用电脑会很刺眼。谢谢~~

**Comment by Kenshin** [comment]
你可以通过自定义样式解决。

快捷键 `o` 打开选项卡，在自定义样式中填入

```
body {
    background-color: #000!important;
}
```

即可搞定。

**Comment by winwangqi** [comment]
> 你可以通过自定义样式解决。
> 
> 快捷键 `o` 打开选项卡，在自定义样式中填入
> 
> ```
> body {
>     background-color: #000!important;
> }
> ```
> 即可搞定。

感谢回复！我试了下您提供的方法，在新打开 tab 的时候，还是会有以**白色**到**黑色**的方式闪烁。如果能够消除闪烁，那就太棒了。

**Comment by Kenshin** [comment]
这是（不可避免）没办法的， Chrome 打开时的颜色无法通过任何方式改变。

我记得 Chrome 出了一款黑色主题的皮肤，你可以试试。

**Comment by Kenshin** [comment]
你可以试试 https://chrome.google.com/webstore/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab 这款主题。

**Comment by winwangqi** [comment]
> 你可以试试 https://chrome.google.com/webstore/detail/just-black/aghfnjkcakhmadgdomlmlhhaocbkloab 这款主题。

谢谢您的回复！我现在用的就是这款主题，正如我上面描述的一样，新打开 tab 还是会闪烁的。

**Comment by Kenshin** [comment]
emmm 这样的话，就没有任何办法了，这已经不是 简 Tab 可以控制的范畴了。

**Comment by winwangqi** [comment]
好的，感谢您开发出这么棒的扩展程序。

**Comment by Kenshin** [comment]
没有问题的话，我将关闭此 issues ~
