### ISSUE TITLE
能否在别的页面也可以开启侧边书签功能

### ISSUE THREAD

**Issue by Mrycp** [Kenshin/simptab#67]
希望在别的页面也可以开启侧边书签功能，很喜欢这个tab，但是我多数qi情况下都是在别的页面打开书签。

**Comment by Kenshin** [comment]
谢谢建议，你说的这种方式暂时不符合简 Tab 的定位。

**Comment by Kenshin** [comment]
没有异议的话，我将关闭此 issues ~
