### ISSUE TITLE
背景较暗时右侧的图标看不清

### ISSUE THREAD

**Issue by greatghoul** [Kenshin/simptab#7]
能否自适应图标的颜色

**Comment by Kenshin** [comment]
新版本（1.4.0）
- 增加了控制栏的快捷键；
- 调整了控制栏的显示方式：鼠标移出/失去焦点时隐藏；反之显示。

新版本还未Publish，但已经到Release阶段，如果对新版本感兴趣的话，我会把新版本发到你的邮箱，请告知邮箱地址。 :)

**Comment by greatghoul** [comment]
greatghoul@gmail.com

谢谢了，很喜欢你的扩展。

**Comment by Kenshin** [comment]
关闭此问题。 :)
