### ISSUE TITLE
增加修改topsites字体的选项

### ISSUE THREAD

**Issue by littlepi** [Kenshin/simptab#70]
topsites默认的字体太小了，而且在页面的最下面，在大屏幕上看不清楚。能否增加修改其字体，以及位置的设置？

**Comment by Kenshin** [comment]
谢谢反馈，你可以使用 [自定义样式](http://ksria.com/simptab/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F) 解决

如果对 CSS 不是很熟悉的话，请告诉我，我来改。

**Comment by littlepi** [comment]
谢谢！我确实不太会css的语法，能否提供个脚本供我参考。就是实现更改位置和字体大小的功能。

**Comment by Kenshin** [comment]
```
.bottom {
   left: <替换这里的数字，默认为0>;
    right: <替换这里的数字，默认为0>;
    bottom: <替换这里的数字，默认为0>;
}

.topsites a {
    font-size: <替换这里的数字>px;
}
```

上面的代码放到  `快捷键 o` 打开后，找到 `自定义样式（ 全局 ）` 放入其中，刷新页面即可。

**Comment by littlepi** [comment]
非常感谢！

**Comment by Kenshin** [comment]
搞定就好，顺便把这个 issues 关闭~
