### ISSUE TITLE
新建标签页背景图的显示动画过渡问题

### ISSUE THREAD

**Issue by bgdizzy** [Kenshin/simptab#71]
作为一个极简tab，在新建tab标签时背景图的加载还是有点慢，另外就是加载过程有点僵硬，过渡不自然，这实在有一点小瑕疵，希望开发者能优化，感谢🙏

：祝工作顺利

**Comment by Kenshin** [comment]
谢谢反馈~

> 新建tab标签时背景图的加载还是有点慢

你说的是，每次更换的新背景吗？如果是的话，这与你的网络环境有关系。比较下载的图质量比较高，所以比较大。

> 加载过程有点僵硬，过渡不自然

指的是更换背景吗？虽然已经优化过了，但确实有些时候感觉生硬些。

**Comment by bgdizzy** [comment]
抱歉没描述清楚，
网络情况差的话可以出个预加载功能，我这边偶尔网速差；
动画过渡问题我在使用中主要是新建标签页的时候，背景图片的加载比较慢，这在一个想快速新建标签页进行搜索的场景下是不够顺畅的，强迫症会等图片加载出来后在搜索😂😂😂，这样整个任务就会出现一次中断。
一直在使用简tab，我觉得简tab要把快做到极致，当初喜欢它也是因为其足够简洁，好像感觉新版本出来没有以前使用中的快了，不知道是不是心理作用

Kenshin Wang <notifications@github.com> 于 2019年4月26日周五 上午8:34写道：

**Comment by Kenshin** [comment]
简 Tab 的机制是预加载，所以当你新建标签页时，加载的是上一张的图片，也就是瞬间载入的，并没有延迟。

不过，极特殊情况下会发生打开新标签页会背景不会马上加载的情况，但应该只限一次，尤其是从禅模式切换过去后才可能发生的问题。

不过，你的提示也很重要，比如： `快做到极致` 确实应该多考虑这些场景转换时的视觉设计。

***

所以，每次新开标签页背景应该都是上次的，只是感觉「显示的变慢」吗？

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，解决了此问题，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](http://ksria.com/simptab/docs/#/选项页?id=时间)

-  [自定义标题栏](http://ksria.com/simptab/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](http://ksria.com/simptab/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](http://ksria.com/simptab/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](http://ksria.com/simptab/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](http://ksria.com/simptab/docs/#/选项页?id=自定义脚本)

-  **新手引导**

***

我将关闭此 issues 有问题请重开。
