### ISSUE TITLE
大神，能不能搞成这样的，不然太不方便了...

### ISSUE THREAD

**Issue by win434545299** [Kenshin/simptab#74]
![image](https://user-images.githubusercontent.com/16912705/58321233-31d46f80-7e50-11e9-892d-c926a6967ef7.png)

**Comment by Kenshin** [comment]
也不错～ 可以借鉴。👍

**Comment by win434545299** [comment]
主要我前端水平太菜了，想改成鼠标划过自动撑开展示全部，怎么都实现不了...只能这样的笨办法了...希望大神下次来个更好的展示方式...= =

**Comment by win434545299** [comment]
另外啥时候可以同步设置啊...= =

**Comment by Kenshin** [comment]
> 主要我前端水平太菜了，想改成鼠标划过自动撑开展示全部，怎么都实现不了...只能这样的笨办法了...希望大神下次来个更好的展示方式...= =

下个版本就会更新~

> 另外啥时候可以同步设置啊...= =

感觉同步没啥实际意义，选项就那几个...

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，解决了此问题，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

主要是优化了 书签栏的 **一级文件夹显示方式** 基本上就是你说的方案，只是稍作调整。

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](http://ksria.com/simptab/docs/#/选项页?id=时间)

-  [自定义标题栏](http://ksria.com/simptab/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](http://ksria.com/simptab/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](http://ksria.com/simptab/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](http://ksria.com/simptab/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](http://ksria.com/simptab/docs/#/选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
