### ISSUE TITLE
是我使用有问题吗？为什么我找不到上传背景图片的地方了

### ISSUE THREAD

**Issue by jsunlove** [Kenshin/simptab#75]
![捕获](https://user-images.githubusercontent.com/22439382/58605771-89009700-82cb-11e9-8e8d-2dac692daf1a.PNG)

**Comment by jsunlove** [comment]
而且大腿的个人网站里也不能进行点击，没法知道上传在哪里

**Comment by Kenshin** [comment]
改为 `随机更换背景` 刷新后再试试。

**Comment by Kenshin** [comment]
嗨，不好意思，久等了，增加了若干新功能，部分功能如下：

-  [12/24 制式转换](http://ksria.com/simptab/docs/#/选项页?id=时间)

-  [自定义标题栏](http://ksria.com/simptab/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](http://ksria.com/simptab/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](http://ksria.com/simptab/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](http://ksria.com/simptab/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](http://ksria.com/simptab/docs/#/选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
