### ISSUE TITLE
能不能定制新标签页标题

### ISSUE THREAD

**Issue by Alalalalaki** [Kenshin/simptab#76]
首先感谢制作。

想找最干净的new tab找到了这个扩展，很满意。但是就是"简 Tab - 新标签页" 几个字看着实在太烦太碍眼了。能不能自定义？或者换成“Pure Tab”这样更干净的表达。

另外我只加载自己上传的图片，应该是本地图片速度却有些慢，有什么改进方法吗？

谢谢

**Comment by Kenshin** [comment]
暂时无法修改这里~
不过，可以考虑标题栏的自定义功能。

**Comment by Alalalalaki** [comment]
多谢考虑。

**Comment by Kenshin** [comment]
嗨，我先重开了这个 issues 这样下次升级时也好通知到你~

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，解决了 [此问题](https://simptab.art/docs/#/选项页?id=自定义标题)，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](http://ksria.com/simptab/docs/#/选项页?id=时间)

-  [自定义标题栏](http://ksria.com/simptab/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](http://ksria.com/simptab/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](http://ksria.com/simptab/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](http://ksria.com/simptab/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](http://ksria.com/simptab/docs/#/选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
