### ISSUE TITLE
禅模式某些网站左上方会限制白点

### ISSUE THREAD

**Issue by pengfd** [Kenshin/simptab#77]
这个功能是干嘛的，能去掉么，每次左边有功能需要选择的时候，它都会弹出来，好烦。。。
![image](https://user-images.githubusercontent.com/41945423/59595435-5f979600-9128-11e9-8de1-22a9ae677c3d.png)

**Comment by Kenshin** [comment]
截图太小，没理解你的意思。

禅模式只在 New Tab 下运行，不会出现在任何有 URL 的 Tab 上。
