### ISSUE TITLE
一直是：地球影像获取中，请稍后；不管是不是开代理都这样，已经很长时间了。

### ISSUE THREAD

**Issue by fengeliangn** [Kenshin/simptab#78]
![image](https://user-images.githubusercontent.com/51092505/61434390-65bba500-a968-11e9-96db-04d94e56683e.png)

**Comment by Kenshin** [comment]
请确保「网络畅通」。

**Comment by fengeliangn** [comment]
> 请确保「网络畅通」。

youtube 4k 的网络 算「网络畅通」吗？

**Comment by Kenshin** [comment]
那必须通。😂

我目前在休假，回去确认下。估计是服务器的配额又满了。

**Comment by fengeliangn** [comment]
辛苦！

**Comment by Kenshin** [comment]
应该是服务器的问题造成的。
下个版本（这几个周）会解决这个问题。

**Comment by Z4Knight** [comment]
感谢！

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，解决了此问题，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](http://ksria.com/simptab/docs/#/选项页?id=时间)

-  [自定义标题栏](http://ksria.com/simptab/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](http://ksria.com/simptab/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](http://ksria.com/simptab/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](http://ksria.com/simptab/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](http://ksria.com/simptab/docs/#/选项页?id=自定义脚本)
-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
