### ISSUE TITLE
收藏或者取消收藏时，侧栏图标有时会消失

### ISSUE THREAD

**Issue by greatghoul** [Kenshin/simptab#8]
![](http://i12.tietuku.com/cf91b097e9886a8e.png)

顶部那个信息提示存在时，鼠标移到侧栏图标时，图标有时会消失，信息提示消失后就又正常了。

版本 1.4.0

**Comment by Kenshin** [comment]
是notification的z-index导致，由于notification短时间会消失，所以没有控制z-index，如果有必要，在下个版本中改善。

**Comment by greatghoul** [comment]
期待中。

**Comment by airycanon** [comment]
我改了 z-index 使 notification 位于 controlbar 的下方，但这样 notification 会被 controlbar 挡住一点，可否把 notification 的位置往左移一点，像这样？
![1](https://cloud.githubusercontent.com/assets/3960628/11772219/1e5c768a-a255-11e5-9070-9165d81ecb96.png)

**Comment by Kenshin** [comment]
嗯，这也是一种解决方案，要比调整z-index简单些，只是需要看看UI/UE是否合适。
等 `1.4.1` 开始开发的时候，我会merge你的代码。 :)

**Comment by Kenshin** [comment]
`1.4.0` 已经发布，关闭这个issues。

**Comment by Kenshin** [comment]
使用
`pointer-events`
即可解决这个问题，不用调整notifaction位置。 :)
