### ISSUE TITLE
初次打开浏览器时，右边功能栏会一闪而过

### ISSUE THREAD

**Issue by huangzhihao233** [Kenshin/simptab#80]
每次最开始打开浏览器时，普通模式/禅模式右边功能栏会一闪而过，如果设置了隐藏常用网址功能，也会出现这种情况，之后新建标签页就不会出现了。

**Comment by Kenshin** [comment]
谢谢反馈。

这「可能」是右侧栏的隐藏时间设置有问题，我会看看如何解决这个问题的。

**Comment by Kenshin** [comment]
嗨，不好意思，久等了。

1.5.5. 已发布，详细请看 [更新日志](https://simptab.art/docs/#/CHANGELOG?id=_155)

由于优化了各种系统性能的问题，所以你可以再试试看。

***

除此之外，增加了若干新功能，部分功能如下：


-  [12/24 制式转换](http://ksria.com/simptab/docs/#/选项页?id=时间)

-  [自定义标题栏](http://ksria.com/simptab/docs/#/选项页?id=自定义标题栏)

-  [禅模式 · 脚本管理器](http://ksria.com/simptab/docs/#/禅模式?id=脚本管理器)

  ![](https://s2.ax1x.com/2019/11/27/Q9Sm8K.png)

-  [全屏](http://ksria.com/simptab/docs/#/控制栏?id=全屏化)

-  [自定义下载文件夹](http://ksria.com/simptab/docs/#/背景源?id=自定义下载位置)

-  [全局性自定义脚本](http://ksria.com/simptab/docs/#/选项页?id=自定义脚本)

-  **新手引导**

并大幅优化了各个界面的 **色彩系统** 与 **打开/关闭** 时的性能问题。

***

我将关闭此 issues 有问题请重开。
