### ISSUE TITLE
希望去掉谷歌字体的加载

### ISSUE THREAD

**Issue by miaowm5** [Kenshin/simptab#83]
新版本简 Tab 加载时会请求谷歌字体，
对于国内的网络环境来说，这一行为意味着每次打开新标签页时，前 10s 左右新标签页是完全空白的……

**Comment by Kenshin** [comment]
谢谢提醒。 😀 

不过，`fonts.googleapis.com` 早就在中国境内了，以下是 `ping` 和 `对于 IP 的查询`

![image](https://user-images.githubusercontent.com/81074/69927026-a2d89c00-14f1-11ea-9441-66c28addd882.png)


![image](https://user-images.githubusercontent.com/81074/69927009-95231680-14f1-11ea-84a3-e04afbb295c0.png)

***

没有其它问题的话，我将关闭这个 issues 有疑问的话，请重新开启。
