### ISSUE TITLE
权限疑问

### ISSUE THREAD

**Issue by vc1** [Kenshin/simptab#88]
`读取和更改您在访问的网站上的所有数据`这个权限是做什么的

**Comment by Kenshin** [comment]
嗨，抱歉，回复的晚了，只因为前几天恰好发布，各种 issues 的信息太多，漏掉了。 😂 

回复你的疑问

***

这个问题是由

https://github.com/Kenshin/simptab/blob/ac7c179214b277eda9a9db9a841b5e556292ecba/manifest.json#L36

引起的，之所以这么做的原因是，简 Tab 的背景源（尤其是来自背景管理器中的背景源）来源比较多样化，导致

https://github.com/Kenshin/simptab/blob/ac7c179214b277eda9a9db9a841b5e556292ecba/manifest.json#L19

已无法满足需求，所以为了简化操作，改为上述方案。
