### ISSUE TITLE
如何删除已经上传的图片？

### ISSUE THREAD

**Issue by yang-ling** [Kenshin/simptab#9]
昨天刚装上simptab，感觉很好，就是上传功能不太直观。我以为上传图片后，背景就会马上替换成我上传的图片，结果没有，所以就上传了好多张，也有一些不雅观的图片。后来在使用中发现，自动换背景的时候，有时候会换上我之前上传的图片，原来上传的意思是上传到图片库啊。
现在问题是，我想删除几张之前上传的图片，但是在设置里面没有找到。如何做到呢？

**Comment by Kenshin** [comment]
hmmm...
暂时没有提供删除功能，`以后会加入删除功能`。

如果想要删除已上传的图片最好的做法是：删除SimpTab，再重新安装它。

图片都是存在Chrome的文件系统里面，比如：
`filesystem:chrome-extension://neodnhemjgeklgmialkjdmifbdbampia/temporary/background.jpg`
这样的地方，安全性没有问题。

**Comment by yang-ling** [comment]
好的，有办法删除就行。

**Comment by Kenshin** [comment]
除了之前的办法外，还有一种方式，这种方式不需要删除SimpTab：
取消所有的背景源，然后刷新New Tab，根据SimpTab的流程，会随机显示Favorite，由于取消了全部的背景源，所以SimpTab读取Favorite的几率增加，当发现有不喜欢的图片时，点击Favorite，即可取消（意味着从Chrome filesystem中删除了这张图片）

**Comment by yang-ling** [comment]
多谢！
