### ISSUE TITLE
my issue

### ISSUE THREAD

**Issue by josephyouxuan** [Kenshin/simptab#90]
您好：
我是一名简tab的用户，很感谢您的制做的优秀的产品。
但是我在使用过程中存在一点问题：
如何更换默认搜索引擎，我想默认使用其他引擎。请指点一下。
谢谢！

**Comment by Kenshin** [comment]
谢谢反馈。

我不是很清楚你说的 **更换默认搜索引擎** 具体是指什么？

简 Tab 并没有所谓默认搜索引擎的概念，它一直都接入了多种搜索引擎，详细请看 [自定义搜索引擎](https://simptab.art/docs/#/%E9%80%89%E9%A1%B9%E9%A1%B5?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e6%90%9c%e7%b4%a2)

所以看看给出的链接是否可以帮到你，否则的话，请详细描述下你的问题。  😀

**Comment by josephyouxuan** [comment]
不好意思，是我那会憨批了，谢谢您的回复，以及您所开发的插件。祝您生活愉快！

**Comment by Kenshin** [comment]
搞定就好，我关闭此 issues ~  😀

**Comment by josephyouxuan** [comment]
好的，麻烦您了

**Comment by Kenshin** [comment]
小问题，祝你用的开心。
