### ISSUE TITLE
禅模式如何使用自定义网址

### ISSUE THREAD

**Issue by Kenshin** [Kenshin/simptab#94]
> ### 每日（次）诗词
> > 借助 https://www.jinrishici.com/ 让你的新标签充满「诗意」~
> 
> ![xnip2019-02-03_14-19-06](https://user-images.githubusercontent.com/81074/52173387-b2e2fa80-27be-11e9-9269-06e4eafc0aa4.jpg)
> 
> [古诗词（竖版 思源宋体 繁体）.txt](https://github.com/Kenshin/simptab/files/2825247/simptab-zenmode-.txt)
> 
> ![default](https://user-images.githubusercontent.com/81074/52173444-e1150a00-27bf-11e9-9b6d-f19eb8b85c14.jpg)
> 
> [今日诗词（横版）.txt](https://github.com/Kenshin/simptab/files/2825248/simptab-zenmode-.txt)

导入这个以后, 无法点击自定义网址, 我只要简单模式的自定义网址就行.

_Originally posted by @xkonglong in https://github.com/Kenshin/simptab/issues/63#issuecomment-610313765_

**Comment by Kenshin** [comment]
请不要在刚才的 issues 下面提问，我帮你新开了一个 issues

***

进入禅模式后，快捷键 s 右下角有关于 自定义网址的显示选项。

**Comment by xkonglong** [comment]
> 请不要在刚才的 issues 下面提问，我帮你新开了一个 issues
> 
> 进入禅模式后，快捷键 s 右下角有关于 自定义网址的显示选项。

这个今日诗词状态下, 自定义网站可以显示, 但是无法点击.  
我看了一下js内容,不涉及对自定义网站的代码

 应该是扩展自身的问题.

**Comment by xkonglong** [comment]
![image](https://user-images.githubusercontent.com/9131496/78738594-d25a5200-7984-11ea-80c4-1d8b1767bb32.png)

**Comment by Kenshin** [comment]
emmm 算是个 Bug 不过也很容易解决，将下面的代码加入到 **自定义样式** 中

```
.bottom-zen-mode {
    z-index: 2000;
}
```

保存刷新后即可。
