### ISSUE TITLE
可否增添设置——让右下角时间只在全屏模式下出现

### ISSUE THREAD

**Issue by 1095533987** [Kenshin/simptab#96]
哇——又爱上了作者你的一个作品😘 简Tab让我沉醉其中，无法自拔。。。。。个人习惯感觉在非全屏状态下Tab标签右下角的时间和系统右下角时间有些重复，然而取消显示时间后在全屏模式下看时间却又不方便，所以才想着是否可以增加一个设置选项，让时间只在全屏模式下出现。

**Comment by 1095533987** [comment]
呃 不知道自定义脚本可否实现我想实现的功能，如果可以，那我就自己鼓捣鼓捣😀

**Comment by Kenshin** [comment]
谢谢喜欢。

应该可以的，自定义脚本只是运行一段 JS 代码，能做的事情很多很多，欢迎捣鼓  😀

**Comment by Kenshin** [comment]
我关闭这个 Issues 了，有需要你再重开它。
