### ISSUE TITLE
如何只是用本地上传的图库，而不从外部寻求图库

### ISSUE THREAD

**Issue by Addmantra** [Kenshin/simptab#98]
Hey，简Tab：
    如题所问，由于我个人对图片比较挑剔，所以有时候出来的图片不是我喜欢的风格，还有一点就是因为假如我在公司，或其他网络较差的地方，打开标签会处于正在加载的空白状态，我猜测是在加载图片的缘故吧。
    还请帮助喔。以上非常感谢。

**Comment by Kenshin** [comment]
1. 上传足够多的本地图片，通过快捷键 `7` 即可开启上传

2. 仅勾选 **随机更换背景** 与下方的 **添加收藏夹背景源**

3. 刷新页面

**Comment by Addmantra** [comment]
Dear Kenshin：
       我光顾着关注设置内的相关配置了，没有留意上层见面的勾选栏。我按您说的配置成功了。
       非常感谢，给您添麻烦你了。很喜欢简Tab，加油。
以上非常感谢！



发件人: Kenshin Wang<mailto:notifications@github.com>
发送时间: 2020年5月22日 11:03
收件人: Kenshin/simptab<mailto:simptab@noreply.github.com>
抄送: Addmantra<mailto:skovxcx@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Kenshin/simptab] 如何只是用本地上传的图库，而不从外部寻求图库 (#98)


  1.  上传足够多的本地图片，通过快捷键 7 即可开启上传
  2.  仅勾选 随机更换背景 与下方的 添加收藏夹背景源
  3.  刷新页面

―

**Comment by Kenshin** [comment]
搞定就好。 👍
