### ISSUE TITLE
怎么才能让侧边书签栏在网页中也能弹出呢

### ISSUE THREAD

**Issue by chenqian3788** [Kenshin/simptab#99]
效果类似
chrome的另外一个扩展[书签侧边栏](https://chrome.google.com/webstore/detail/bookmark-sidebar/jdbnofccmhefkmjbkkdkfiicjkgofkdh?hl=zh-CN)

**Comment by Kenshin** [comment]
谢谢反馈。

目前 简 Tab 没有这样的功能，因为这个功能与 简 Tab 的设计初衷相悖。

所以，你可以同时使用这两个扩展，并不影响什么。😀
